make failures more verbose
spothero/api-test pull request #13
Opened 2017-01-23 22:33 UTC by ellmanj

Please review: @ash6851 @spothero/backend 

This PR prints the expected schema from documentation, as well as the actual response body, when certain kinds of test failures happen. This should help with debugging. It produces test output like [this](https://gist.github.com/ellmanj/713fb48b5231a116df15e105a796620e).

This might not be the "right" way to do this. Probably better to use the nose [`formatFailure()`](http://nose.readthedocs.io/en/latest/plugins/interface.html#nose.plugins.base.IPluginInterface.formatFailure) function, but I was having a hard time getting that to work.

2017-01-26 19:30 UTC, ash6851 requested changes
@ellmanj super minor things!

2017-01-26 19:30 UTC, ash6851 commented on api_test/test_cases.py
> +            print('Failure:\n'
can we switch this to a logger?

2017-01-26 19:30 UTC, ash6851 commented on api_test/test_cases.py
> +            compare_actual_to_definition(self.response['schema'], body)
can we wrap these individually so we know which one causes the error?

2017-02-01 20:47 UTC, ellmanj commented
@ash6851 please take another look!

2017-02-13 14:59 UTC, ash6851 approved these changes

2017-02-13 15:14 UTC, merged